.TH "AStar" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AStar
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <AStar\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIsPositionValid\fP (const \fBVector2Int\fP position, const std::shared_ptr< std::vector< std::vector< bool > > > grid, const \fBVector2Int\fP start, const \fBVector2Int\fP goal)"
.br
.ti -1c
.RI "static std::vector< \fBVector2Int\fP > \fBDirectionPath\fP (const \fBVector2Int\fP start, const \fBVector2Int\fP goal, const std::shared_ptr< std::vector< std::vector< bool > > > grid)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::vector< \fBVector2Int\fP > AStar::DirectionPath (const \fBVector2Int\fP start, const \fBVector2Int\fP goal, const std::shared_ptr< std::vector< std::vector< bool > > > grid)\fR [static]\fP"

.SS "bool AStar::IsPositionValid (const \fBVector2Int\fP position, const std::shared_ptr< std::vector< std::vector< bool > > > grid, const \fBVector2Int\fP start, const \fBVector2Int\fP goal)\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
