.TH "out/build Directory Reference" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
out/build Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBlinux\-debug\fP"
.br
.ti -1c
.RI "directory \fBwindows\-base\fP"
.br
.ti -1c
.RI "directory \fBx86\-debug\fP"
.br
.in -1c
