.TH "src/Colors.h" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Colors.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPLAYER_COLOR\fP   COLOR_GREEN"
.br
.ti -1c
.RI "#define \fBTREASURE_COLOR\fP   COLOR_YELLOW"
.br
.ti -1c
.RI "#define \fBPROJECTILE_COLOR\fP   COLOR_CYAN"
.br
.ti -1c
.RI "#define \fBENEMY_COLOR\fP   COLOR_RED"
.br
.ti -1c
.RI "#define \fBCAVE_COLOR\fP   8"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CAVE_COLOR   8"

.SS "#define ENEMY_COLOR   COLOR_RED"

.SS "#define PLAYER_COLOR   COLOR_GREEN"

.SS "#define PROJECTILE_COLOR   COLOR_CYAN"

.SS "#define TREASURE_COLOR   COLOR_YELLOW"

.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
