.TH "CompareNode" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompareNode
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Node\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const std::shared_ptr< \fBNode\fP > a, const std::shared_ptr< \fBNode\fP > b) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool CompareNode::operator() (const std::shared_ptr< \fBNode\fP > a, const std::shared_ptr< \fBNode\fP > b) const"


.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
