.TH "Damage" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Damage
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Damage\&.h>\fP
.PP
Inherited by \fBFieldObject\fP\fR [virtual]\fP, and \fBFood\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual float \fBGetDamage\fP () const"
.br
.ti -1c
.RI "\fBDamage\fP ()"
.br
.ti -1c
.RI "\fBDamage\fP (float \fBdamage\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fBdamage\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Damage::Damage ()"

.SS "Damage::Damage (float damage)"

.SH "Member Function Documentation"
.PP 
.SS "float Damage::GetDamage () const\fR [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float Damage::damage = 0\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
