.TH "src/Enemy.h" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Enemy.h
.SH SYNOPSIS
.br
.PP
\fR#include <random>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include 'AStar\&.h'\fP
.br
\fR#include 'Soldier\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnemy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
