.TH "FieldObject" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldObject
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FieldObject\&.h>\fP
.PP
Inherits \fBLife\fP, and \fBDamage\fP\&.
.PP
Inherited by \fBProjectile\fP, and \fBSoldier\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBSpeed\fP () const"
.br
.ti -1c
.RI "int \fBTeamColor\fP () const"
.br
.ti -1c
.RI "bool \fBIsMoving\fP () const"
.br
.ti -1c
.RI "virtual bool \fBRemoveOnCollision\fP () const"
.br
.ti -1c
.RI "virtual \fBVector2Int\fP \fBNextDirection\fP ()=0"
.br
.ti -1c
.RI "virtual unsigned char \fBDisplayChar\fP () const =0"
.br
.ti -1c
.RI "\fBVector2Int\fP \fBPosition\fP () const"
.br
.ti -1c
.RI "\fBVector2Int\fP \fBDirection\fP () const"
.br
.ti -1c
.RI "\fBVector2Int\fP \fBNextPosition\fP (\fBVector2Int\fP dir) const"
.br
.ti -1c
.RI "\fBVector2Int\fP \fBPreviousPosition\fP () const"
.br
.ti -1c
.RI "void \fBMove\fP (\fBVector2Int\fP dir)"
.br
.ti -1c
.RI "void \fBSetMoving\fP (bool moving)"
.br
.ti -1c
.RI "void \fBSetPosition\fP (\fBVector2Int\fP newPosition)"
.br
.ti -1c
.RI "void \fBSetDirection\fP (\fBVector2Int\fP newDirection)"
.br
.ti -1c
.RI "void \fBSetCave\fP (std::shared_ptr< std::vector< std::vector< bool > > > field)"
.br
.ti -1c
.RI "bool \fBWillCollideWithCave\fP (\fBVector2Int\fP dir) const"
.br
.ti -1c
.RI "bool \fBWillGoOutOfBounds\fP (\fBVector2Int\fP dir) const"
.br
.in -1c

Public Member Functions inherited from \fBLife\fP
.in +1c
.ti -1c
.RI "virtual float \fBHealth\fP () const"
.br
.ti -1c
.RI "virtual void \fBChangeHealth\fP (float amount)"
.br
.ti -1c
.RI "virtual bool \fBIsDead\fP () const"
.br
.ti -1c
.RI "\fBLife\fP ()"
.br
.ti -1c
.RI "\fBLife\fP (float \fBstartingHealth\fP)"
.br
.in -1c

Public Member Functions inherited from \fBDamage\fP
.in +1c
.ti -1c
.RI "virtual float \fBGetDamage\fP () const"
.br
.ti -1c
.RI "\fBDamage\fP ()"
.br
.ti -1c
.RI "\fBDamage\fP (float \fBdamage\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBFieldObject\fP (int \fBteamColor\fP, int \fBspeed\fP, \fBVector2Int\fP \fBposition\fP, \fBVector2Int\fP \fBdirection\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBspeed\fP"
.br
.ti -1c
.RI "int \fBteamColor\fP"
.br
.ti -1c
.RI "bool \fBisMoving\fP"
.br
.ti -1c
.RI "\fBVector2Int\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBVector2Int\fP \fBdirection\fP"
.br
.ti -1c
.RI "\fBVector2Int\fP \fBpreviousPosition\fP"
.br
.ti -1c
.RI "std::shared_ptr< std::vector< std::vector< bool > > > \fBcave\fP"
.br
.in -1c

Protected Attributes inherited from \fBLife\fP
.in +1c
.ti -1c
.RI "float \fBstartingHealth\fP"
.br
.ti -1c
.RI "float \fBcurrentHealth\fP"
.br
.in -1c

Protected Attributes inherited from \fBDamage\fP
.in +1c
.ti -1c
.RI "float \fBdamage\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldObject::FieldObject (int teamColor, int speed, \fBVector2Int\fP position, \fBVector2Int\fP direction)\fR [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBVector2Int\fP FieldObject::Direction () const"

.SS "virtual unsigned char FieldObject::DisplayChar () const\fR [pure virtual]\fP"

.PP
Implemented in \fBProjectile\fP, and \fBSoldier\fP\&.
.SS "bool FieldObject::IsMoving () const"

.SS "void FieldObject::Move (\fBVector2Int\fP dir)"

.SS "virtual \fBVector2Int\fP FieldObject::NextDirection ()\fR [pure virtual]\fP"

.PP
Implemented in \fBEnemy\fP, \fBProjectile\fP, and \fBSoldier\fP\&.
.SS "\fBVector2Int\fP FieldObject::NextPosition (\fBVector2Int\fP dir) const"

.SS "\fBVector2Int\fP FieldObject::Position () const"

.SS "\fBVector2Int\fP FieldObject::PreviousPosition () const"

.SS "bool FieldObject::RemoveOnCollision () const\fR [virtual]\fP"

.PP
Reimplemented in \fBProjectile\fP\&.
.SS "void FieldObject::SetCave (std::shared_ptr< std::vector< std::vector< bool > > > field)"

.SS "void FieldObject::SetDirection (\fBVector2Int\fP newDirection)"

.SS "void FieldObject::SetMoving (bool moving)"

.SS "void FieldObject::SetPosition (\fBVector2Int\fP newPosition)"

.SS "int FieldObject::Speed () const"

.SS "int FieldObject::TeamColor () const"

.SS "bool FieldObject::WillCollideWithCave (\fBVector2Int\fP dir) const"

.SS "bool FieldObject::WillGoOutOfBounds (\fBVector2Int\fP dir) const"

.SH "Member Data Documentation"
.PP 
.SS "std::shared_ptr<std::vector<std::vector<bool> > > FieldObject::cave\fR [protected]\fP"

.SS "\fBVector2Int\fP FieldObject::direction\fR [protected]\fP"

.SS "bool FieldObject::isMoving\fR [protected]\fP"

.SS "\fBVector2Int\fP FieldObject::position\fR [protected]\fP"

.SS "\fBVector2Int\fP FieldObject::previousPosition\fR [protected]\fP"

.SS "int FieldObject::speed\fR [protected]\fP"

.SS "int FieldObject::teamColor\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
