.TH "GameField" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameField
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <GameField\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBTick\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBDraw\fP () const"
.br
.ti -1c
.RI "bool \fBIsOutOfBounds\fP (const \fBVector2Int\fP position) const"
.br
.ti -1c
.RI "bool \fBMakeFieldMove\fP (const std::shared_ptr< \fBFieldObject\fP > object)"
.br
.ti -1c
.RI "void \fBAddFieldObject\fP (const std::shared_ptr< \fBFieldObject\fP > object)"
.br
.ti -1c
.RI "std::shared_ptr< \fBFieldObject\fP > \fBHit\fP (std::shared_ptr< \fBFieldObject\fP > obj, \fBVector2Int\fP pos) const"
.br
.ti -1c
.RI "bool \fBCheckHit\fP (const std::shared_ptr< \fBFieldObject\fP > obj) const"
.br
.ti -1c
.RI "bool \fBReachedPlayer\fP (const std::shared_ptr< \fBFieldObject\fP > obj) const"
.br
.ti -1c
.RI "\fBGameField\fP (\fBVector2Int\fP size, \fBVector2Int\fP padding, std::shared_ptr< \fBPlayer\fP > player, float fillProbability, int iterations)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameField::GameField (\fBVector2Int\fP size, \fBVector2Int\fP padding, std::shared_ptr< \fBPlayer\fP > player, float fillProbability, int iterations)"

.SH "Member Function Documentation"
.PP 
.SS "void GameField::AddFieldObject (const std::shared_ptr< \fBFieldObject\fP > object)"

.SS "bool GameField::CheckHit (const std::shared_ptr< \fBFieldObject\fP > obj) const"

.SS "void GameField::Draw () const"

.SS "std::shared_ptr< \fBFieldObject\fP > GameField::Hit (std::shared_ptr< \fBFieldObject\fP > obj, \fBVector2Int\fP pos) const"

.SS "void GameField::Init ()"

.SS "bool GameField::IsOutOfBounds (const \fBVector2Int\fP position) const"

.SS "bool GameField::MakeFieldMove (const std::shared_ptr< \fBFieldObject\fP > object)"

.SS "bool GameField::ReachedPlayer (const std::shared_ptr< \fBFieldObject\fP > obj) const"

.SS "bool GameField::Tick ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
