.TH "Gridshot.h" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gridshot.h
.SH SYNOPSIS
.br
.PP
\fR#include <ctime>\fP
.br
\fR#include <mutex>\fP
.br
\fR#include <string>\fP
.br
\fR#include <random>\fP
.br
\fR#include <thread>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include 'src/Colors\&.h'\fP
.br
\fR#include <src/Enemy\&.h>\fP
.br
\fR#include 'src/Soldier\&.h'\fP
.br
\fR#include 'src/GameField\&.h'\fP
.br
\fR#include 'src/Projectile\&.h'\fP
.br
\fR#include 'src/FieldObject\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCAVE_COLOR\fP   8"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBThread\fP = std::thread"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CAVE_COLOR   8"

.SH "Typedef Documentation"
.PP 
.SS "using \fBThread\fP = std::thread"

.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
