.TH "src/Item.h" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Item.h
.SH SYNOPSIS
.br
.PP
\fR#include <memory>\fP
.br
\fR#include 'Player\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItem\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
