.TH "src/Life.h" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Life.h
.SH SYNOPSIS
.br
.PP
\fR#include <algorithm>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLife\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
