.TH "Life" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Life
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Life\&.h>\fP
.PP
Inherited by \fBFieldObject\fP\fR [virtual]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual float \fBHealth\fP () const"
.br
.ti -1c
.RI "virtual void \fBChangeHealth\fP (float amount)"
.br
.ti -1c
.RI "virtual bool \fBIsDead\fP () const"
.br
.ti -1c
.RI "\fBLife\fP ()"
.br
.ti -1c
.RI "\fBLife\fP (float \fBstartingHealth\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fBstartingHealth\fP"
.br
.ti -1c
.RI "float \fBcurrentHealth\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Life::Life ()"

.SS "Life::Life (float startingHealth)"

.SH "Member Function Documentation"
.PP 
.SS "void Life::ChangeHealth (float amount)\fR [virtual]\fP"

.SS "float Life::Health () const\fR [virtual]\fP"

.SS "bool Life::IsDead () const\fR [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float Life::currentHealth\fR [protected]\fP"

.SS "float Life::startingHealth\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
