.TH "src/Player.h" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Player.h
.SH SYNOPSIS
.br
.PP
\fR#include 'Score\&.h'\fP
.br
\fR#include 'Soldier\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
