.TH "Score" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Score
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Score\&.h>\fP
.PP
Inherited by \fBPlayer\fP, and \fBTreasure\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScore\fP ()"
.br
.ti -1c
.RI "\fBScore\fP (int startingScore)"
.br
.ti -1c
.RI "int \fBGetScore\fP () const"
.br
.ti -1c
.RI "void \fBChangeScore\fP (int amount)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBscore\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Score::Score ()"

.SS "Score::Score (int startingScore)"

.SH "Member Function Documentation"
.PP 
.SS "void Score::ChangeScore (int amount)"

.SS "int Score::GetScore () const"

.SH "Member Data Documentation"
.PP 
.SS "int Score::score\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
