.TH "Vector2IntHash" 3 "Version 0.0.1" "Gridshot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector2IntHash
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Vector2Int\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::size_t \fBoperator()\fP (const \fBVector2Int\fP &v) const noexcept"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::size_t Vector2IntHash::operator() (const \fBVector2Int\fP & v) const\fR [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Gridshot from the source code\&.
