Gridshot.cpp
﻿ int height
Referenced by CursesInit, GameLoop.
﻿ int width
Referenced by CursesInit, GameLoop.
GameField* gameField
Referenced by GameLoop.
const std::string gameover
Referenced by main.
const std::string title
Referenced by main.
const unsigned char emptyBar
const unsigned char fullBar
static const std::string HealthBar(float min, float max, float current)
void CursesInit()
References CAVE_COLOR, ENEMY_COLOR, height, PLAYER_COLOR, TREASURE_COLOR, width.
Referenced by main.
void CursesClose()
Referenced by main.
void GameLoop()
References GameField::AddFieldObject, Vector2Int::Down, GameField::Draw, gameField, height, GameField::Init, Vector2Int::Left, PLAYER_COLOR, PROJECTILE_COLOR, Vector2Int::Right, GameField::Tick, Vector2Int::Up, width.
Referenced by main.
int main()
References CursesClose, CursesInit, GameLoop, gameover, title.