CaveGenerator
std::shared_ptr<std::vector<std::vector<bool> > > CaveGenerator::cave
float CaveGenerator::fillProbability
Vector2Int CaveGenerator::size
std::vector<Vector2Int> CaveGenerator::emptySpaces
void CaveGenerator::CaveIteration()
void CaveGenerator::GenerateInitialCave()
int CaveGenerator::CountSolidNeighbors(const int x, const int y) const
CaveGenerator::CaveGenerator(Vector2Int size, float fillProbability)
void CaveGenerator::GenerateCave(const int iterations, const Vector2Int *size, const float *fillProbability)
Referenced by GameField::GameField.
std::shared_ptr< std::vector< std::vector< bool > > > CaveGenerator::GetCave() const
Referenced by GameField::AddFieldObject, GameField::Draw, GameField::Init, GameField::Tick.
Vector2Int CaveGenerator::GetSize() const
Referenced by GameField::Draw.
int CaveGenerator::GetEmptySpaces() const
Referenced by GameField::GameField.
Vector2Int CaveGenerator::GetRandomEmptySpace()
References Vector2Int::x, Vector2Int::y.
Referenced by GameField::GameField.
Vector2Int CaveGenerator::GetEnemySpace(const Vector2Int fromPosition, const int minDistance)
References GetRandomDistantEmptySpace, Vector2Int::x, Vector2Int::y.
Referenced by GameField::GameField.
Vector2Int CaveGenerator::GetRandomDistantEmptySpace(const Vector2Int fromPosition, const int minDistance)
References Vector2Int::Distance, Vector2Int::Zero.
Referenced by GameField::GameField, GetEnemySpace.