GameField
Vector2Int GameField::size
Vector2Int GameField::padding
CaveGenerator* GameField::caveGenerator
FieldObjectList GameField::fieldObjects
ItemMap GameField::itemMap
ObjectMap GameField::objectMap
std::shared_ptr<Player> GameField::player
bool GameField::Tick()
References CheckHit, ENEMY_COLOR, CaveGenerator::GetCave, IsOutOfBounds, MakeFieldMove, ReachedPlayer, Vector2Int::x, Vector2Int::y.
Referenced by GameLoop.
void GameField::Init()
References CaveGenerator::GetCave.
Referenced by GameLoop.
void GameField::Draw() const
References CAVE_COLOR, CaveGenerator::GetCave, CaveGenerator::GetSize, Vector2Int::x, Vector2Int::y.
Referenced by GameLoop.
bool GameField::IsOutOfBounds(const Vector2Int position) const
References Vector2Int::x, Vector2Int::y.
Referenced by Tick.
bool GameField::MakeFieldMove(const std::shared_ptr< FieldObject > object)
Referenced by Tick.
void GameField::AddFieldObject(const std::shared_ptr< FieldObject > object)
References CaveGenerator::GetCave.
Referenced by GameLoop.
std::shared_ptr< FieldObject > GameField::Hit(std::shared_ptr< FieldObject > obj, Vector2Int pos) const
Referenced by CheckHit.
bool GameField::CheckHit(const std::shared_ptr< FieldObject > obj) const
References Hit.
Referenced by Tick.
bool GameField::ReachedPlayer(const std::shared_ptr< FieldObject > obj) const
References Vector2Int::Down, Vector2Int::Left, Vector2Int::Right, Vector2Int::Up.
Referenced by Tick.
GameField::GameField(Vector2Int size, Vector2Int padding, std::shared_ptr< Player > player, float fillProbability, int iterations)
References ENEMY_COLOR, CaveGenerator::GenerateCave, CaveGenerator::GetEmptySpaces, CaveGenerator::GetEnemySpace, CaveGenerator::GetRandomDistantEmptySpace, CaveGenerator::GetRandomEmptySpace, Vector2Int::Zero.