Vector2Int
int Vector2Int::x
Referenced by Distance, GameField::Draw, CaveGenerator::GetEnemySpace, CaveGenerator::GetRandomEmptySpace, GameField::IsOutOfBounds, AStar::IsPositionValid, ManhattanDistance, FieldObject::Move, Move, operator+, operator-, operator-, operator/, operator/, operator<, operator==, Sum, GameField::Tick, FieldObject::WillCollideWithCave, FieldObject::WillGoOutOfBounds.
int Vector2Int::y
Referenced by GameField::Draw, CaveGenerator::GetEnemySpace, CaveGenerator::GetRandomEmptySpace, GameField::IsOutOfBounds, AStar::IsPositionValid, ManhattanDistance, FieldObject::Move, Move, operator+, operator-, operator-, operator/, operator/, operator<, operator==, GameField::Tick, FieldObject::WillCollideWithCave, FieldObject::WillGoOutOfBounds.
const Vector2Int Vector2Int::Up
Referenced by AStar::DirectionPath, GameLoop, GameField::ReachedPlayer.
const Vector2Int Vector2Int::Down
Referenced by GameLoop, GameField::ReachedPlayer.
const Vector2Int Vector2Int::Left
Referenced by GameLoop, GameField::ReachedPlayer.
const Vector2Int Vector2Int::Right
Referenced by AStar::DirectionPath, GameLoop, GameField::ReachedPlayer.
const Vector2Int Vector2Int::Zero
Referenced by GameField::GameField, CaveGenerator::GetRandomDistantEmptySpace, Enemy::NextDirection, FieldObject::WillCollideWithCave, FieldObject::WillGoOutOfBounds.
const std::vector< Vector2Int > Vector2Int::Directions
Vector2Int::Vector2Int()
Referenced by operator/.
Vector2Int::Vector2Int(int x, int y)
void Vector2Int::Move(Vector2Int direction)
References x, y.
Referenced by FieldObject::Move.
Vector2Int Vector2Int::operator-() const
References x, y.
Vector2Int Vector2Int::operator-(Vector2Int other) const
References x, y.
Vector2Int Vector2Int::operator/(int scalar) const
References Vector2Int, x, y.
Vector2Int Vector2Int::operator+(Vector2Int other) const
References x, y.
Vector2Int Vector2Int::operator/(Vector2Int other) const
References x, y.
bool Vector2Int::operator==(Vector2Int other) const
References x, y.
bool Vector2Int::operator<(const Vector2Int other) const
References x, y.
int Vector2Int::ManhattanDistance(const Vector2Int other) const
References x, y.
Referenced by AStar::DirectionPath.
Vector2Int Vector2Int::Sum(Vector2Int vec1, Vector2Int vec2)
References x.
Referenced by FieldObject::NextPosition.
int Vector2Int::Distance(Vector2Int vec1, Vector2Int vec2)
References x.
Referenced by CaveGenerator::GetRandomDistantEmptySpace, Enemy::NextDirection.